#!/bin/bash
# ======================================================================
# This file was automatically generated by SbatchMan.
# Do not edit this file directly.
# ======================================================================

#SBATCH --job-name={JOB_NAME}
#SBATCH --output={EXP_DIR}/stdout.log
#SBATCH --error={EXP_DIR}/stderr.log
#SBATCH --partition=short
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --account=flavio.vella
#SBATCH --time=01:00:00
#SBATCH --gres=gpu:0

# Change to the submission directory
cd "{CWD}"

# Update job_id in metadata.yaml
perl -i -pe"s/job_id: [0-9]*/job_id: $SLURM_JOB_ID/" "{EXP_DIR}/metadata.yaml"

# Update status to RUNNING
if [ -f "{EXP_DIR}/metadata.yaml" ]; then
 perl -i -pe's/status: .*/status: RUNNING/' {EXP_DIR}/metadata.yaml
fi

# (Optional) Preprocess command
{PREPROCESS}

# User command
{CMD}
EXIT_CODE=$?

# Update status to COMPLETED or FAILED
if [ -f "{EXP_DIR}/metadata.yaml" ]; then
  if [ $EXIT_CODE -eq 0 ]; then
    perl -i -pe's/status: .*/status: COMPLETED/' {EXP_DIR}/metadata.yaml
  else
    perl -i -pe's/status: .*/status: FAILED/' {EXP_DIR}/metadata.yaml
  fi
  perl -i -pe"s/exitcode: .*/exitcode: $EXIT_CODE/" {EXP_DIR}/metadata.yaml
fi

# (Optional) Postprocess command
{POSTPROCESS}

exit $EXIT_CODE