variables:
  mtx: 'datasets/matrices_list_mtx.txt'
  perm: 
    - random1D
    - SB_degree
    - SB_gray
    - SB_slashburn
    - SPARTA_reorder

preprocess: |
  source ~/.venv/bin/activate
  mtx_name=$(basename {mtx} .mtx)

jobs:
  - config: "perm"
    config_jobs:
      - tag: "ANALYSIS_ROW"
        command: "python3 MtxPerm/ANALYSIS/analyze.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ROW --block-sizes 4 8 16 32 64 128"
