variables:
  mtx: 'datasets/matrices_list_mtx.txt'
  perm: 
    - random1D
    - SB_amd
  #  - SB_degree
  #  - SB_metis
  #  - SB_rcm
  #  - SB_rabbit
  #  - SB_patoh

preprocess: |
  source ~/.venv/bin/activate
  mtx_name=$(basename {mtx} .mtx)
  module load CUDA/

jobs:
  - config: "gpu"
    config_jobs:
      - tag: "ANALYSIS_SYMMETRIC"
        command: "python3 MtxPerm/ANALYSIS/analyze.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type SYMMETRIC --block-sizes 4 8 16 32 64 128 --pretty"
