variables:
  mtx: 'datasets/matrices_list_mtx.txt'
  perm:
    - random1D
    - SB_amd
    - SB_gray
    - SB_degree
    - SB_metis
    - SB_rcm
    - SB_rabbit
    - SB_patoh
    - SB_slashburn
    - GROOT_reorder
    - SPARTA_reorder
  n_cols:
    - 32
    - 256
    - 1024

preprocess: |
  source operators/flashsparse_preprocess.sh
  mtx_name=$(basename {mtx} .mtx)

jobs:
  - config: "gpu"
    config_jobs:
      # No reordering
      - tag: "FLASHSPARSE_SPMM_NO_REORDER"
        command: "python3 operators/flashsparse_spmm.py {mtx} --n-cols {n_cols}"

      # Row reordering (P*A)
      - tag: "FLASHSPARSE_SPMM_ROW"
        command: "python3 operators/flashsparse_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ROW --n-cols {n_cols}"

      # Symmetric reordering (P*A*P^T)
      - tag: "FLASHSPARSE_SPMM_SYMMETRIC"
        command: "python3 operators/flashsparse_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type SYMMETRIC --n-cols {n_cols}"
