variables:
  mtx: 'datasets/matrices_list_mtx.txt'
  perm: 
    - random2D
  block_size:
    - 8
    - 32

preprocess: |
  source ~/.venv/bin/activate
  mtx_name=$(basename {mtx} .mtx)
  module load CUDA/

jobs:
  - config: "gpu"
    config_jobs:

      - tag: "CUSPARSE_SPMV_BSR_ASYMMETRIC"
        command: "python3 operators/cusparse_bsr_spmv.py {mtx} --perm perms/{perm}/$mtx_name.perm --blocksize {block_size} --perm-type ASYMMETRIC"
      - tag: "CUSPARSE_SPMV_CSR_ASYMMETRIC"
        command: "python3 operators/cusparse_csr_spmv.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ASYMMETRIC"

      - tag: "CUSPARSE_SPMM_BSR_ASYMMETRIC"
        command: "python3 operators/cusparse_bsr_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --blocksize {block_size} --perm-type ASYMMETRIC"
      - tag: "CUSPARSE_SPMM_CSR_ASYMMETRIC"
        command: "python3 operators/cusparse_csr_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ASYMMETRIC"