variables:
  mtx: 'datasets/matrices_list_filtered.txt'
  perm: 
    - random2D
  block_size:
    - 32
  n_cols:
    - 32
    - 256
    - 1024

preprocess: |
  source ~/.venv/bin/activate
  mtx_name=$(basename {mtx} .mtx)
  module load CUDA/
  module load GCC/13.3.0

jobs:
  - config: "gpu"
    config_jobs:

      - tag: "ASPT_SPMM_ASYMMETRIC"
        command: "python3 operators/aspt_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ASYMMETRIC --n-cols {n_cols}"

      - tag: "DTC_SPMM_ASYMMETRIC"
        preprocess: |
          module purge
          module load CUDA/
          module load GCC/13.3.0
          source ~/.conda/envs/DTCSpMM/bin/activate
          mtx_name=$(basename {mtx} .mtx)
        command: "python3 operators/dtc_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ASYMMETRIC --n-cols {n_cols} --n-iterations 1"

#      - tag: "CUSPARSE_SPMV_BSR_ASYMMETRIC"
#        command: "python3 operators/cusparse_bsr_spmv.py {mtx} --perm perms/{perm}/$mtx_name.perm --blocksize {block_size} --perm-type ASYMMETRIC"
#      - tag: "CUSPARSE_SPMV_CSR_ASYMMETRIC"
#        command: "python3 operators/cusparse_csr_spmv.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ASYMMETRIC"

      - tag: "CUSPARSE_SPMM_BSR_ASYMMETRIC"
        command: "python3 operators/cusparse_bsr_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --blocksize {block_size} --perm-type ASYMMETRIC --n-cols {n_cols}"
      - tag: "CUSPARSE_SPMM_CSR_ASYMMETRIC"
        command: "python3 operators/cusparse_csr_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ASYMMETRIC --n-cols {n_cols}"

      - tag: "SMAT_SPMM_ASYMMETRIC"
        command: "python3 operators/smat_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --blocksize {block_size} --perm-type ASYMMETRIC --n-cols {n_cols}"

      - tag: "ACCSPMM_SPMM_ASYMMETRIC"
        command: "python3 operators/accspmm_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type ASYMMETRIC --n-cols {n_cols}"