variables:
  mtx: 'datasets/matrices_list_mtx.txt'
  perm: 
    - random1D
    - SB_amd
  #  - SB_degree
  #  - SB_metis
  #  - SB_rcm
  #  - SB_rabbit
  #  - SB_patoh
  block_size:
    - 32

preprocess: |
  source ~/.venv/bin/activate
  mtx_name=$(basename {mtx} .mtx)
  module load CUDA/

jobs:
  - config: "gpu"
    config_jobs:

#      - tag: "CUSPARSE_SPMV_BSR_SYMMETRIC"
#        command: "python3 operators/cusparse_bsr_spmv.py {mtx} --perm perms/{perm}/$mtx_name.perm --blocksize {block_size} --perm-type SYMMETRIC"
#      - tag: "CUSPARSE_SPMV_CSR_SYMMETRIC"
#        command: "python3 operators/cusparse_csr_spmv.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type SYMMETRIC"

      - tag: "CUSPARSE_SPMM_BSR_SYMMETRIC"
        command: "python3 operators/cusparse_bsr_spmm_wrapper.py {mtx} --perm perms/{perm}/$mtx_name.perm --blocksize {block_size} --perm-type SYMMETRIC"
      - tag: "CUSPARSE_SPMM_CSR_SYMMETRIC"
        command: "python3 operators/cusparse_csr_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --perm-type SYMMETRIC"

      - tag: "SMAT_SPMM_SYMMETRIC"
        command: "python3 operators/smat_spmm.py {mtx} --perm perms/{perm}/$mtx_name.perm --blocksize {block_size} --perm-type SYMMETRIC"