variables:
  mtx: 'datasets/matrices_list_mtx.txt'
preprocess: |
    mtx_name=$(basename {mtx} .mtx)
    source ~/.venv/bin/activate

jobs:
  - config: "perm"
    config_jobs:

      - tag: "random1D"
        preprocess: |
          mkdir -p perms/random1D
          perm_path=perms/random1D/$mtx_name.perm
        command: "python3 MtxPerm/RANDOM/GB_random_permutation_1d.py {mtx} --output $perm_path"

      - tag: "random2D"
        preprocess: |
          mkdir -p perms/random2D
          perm_path=perms/random2D/$mtx_name.perm
        command: "python3 MtxPerm/RANDOM/GB_random_permutation_2d.py {mtx} --output $perm_path"

      - tag: "SB_degree"
        preprocess: |
          mkdir -p perms/SB_degree
          perm_path=perms/SB_degree/$mtx_name.perm
        command: "./MtxPerm/SPARSEBASE/build/degree_perm {mtx} $perm_path"

      - tag: "SB_gray"
        preprocess: |
          mkdir -p perms/SB_gray
          perm_path=perms/SB_gray/$mtx_name.perm
        command: "./MtxPerm/SPARSEBASE/build/gray_perm {mtx} $perm_path"

      - tag: "SB_rcm"
        preprocess: |
          mkdir -p perms/SB_rcm
          perm_path=perms/SB_rcm/$mtx_name.perm
        command: "./MtxPerm/SPARSEBASE/build/rcm_perm {mtx} $perm_path"

      - tag: "SB_metis"
        preprocess: |
          mkdir -p perms/SB_metis
          perm_path=perms/SB_metis/$mtx_name.perm
        command: "./MtxPerm/SPARSEBASE/build/metis_perm {mtx} $perm_path --niter 1"

      - tag: "SB_amd"
        preprocess: |
          mkdir -p perms/SB_amd
          perm_path=perms/SB_amd/$mtx_name.perm
        command: "./MtxPerm/SPARSEBASE/build/amd_perm {mtx} $perm_path"

      - tag: "SB_rabbit"
        preprocess: |
          mkdir -p perms/SB_rabbit
          perm_path=perms/SB_rabbit/$mtx_name.perm
        command: "./MtxPerm/SPARSEBASE/build/rabbit_perm {mtx} $perm_path"

      - tag: "SB_patoh"
        preprocess: |
          mkdir -p perms/SB_patoh
          perm_path=perms/SB_patoh/$mtx_name.perm
        command: "./MtxPerm/SPARSEBASE/build/patoh_perm {mtx} $perm_path"