variables:
  mtx: 'datasets/matrices_list_mtx.txt'
  perm: 
    - "graphblas"
    - "SB_degree"
    - "SB_gray"
    - "SB_rcm"

preprocess: |
  source ~/.venv/bin/activate
  mtx_name=$(basename {mtx} .mtx)
  perm_path=perms/{perm}/$mtx_name.perm
  module load CUDA/

jobs:
  - config: "gpu"
    config_jobs:

      - tag: "CuSPARSE_CSR_SPMM"
        command: "python3 operators/cusparse_csr_spmm.py {mtx} --perm_rows $perm_path --perm_cols $perm_path"
