variables:
  mtx: 'datasets/matrices_list_mtx.txt'
  perm: 
    - "graphblas"

preprocess: |
  source ~/.venv/bin/activate
  mtx_name=$(basename {mtx})
  module load CUDA/

jobs:
  - config: "SpMV"
    config_jobs:

      - tag: "CuSPARSE"
        command: "./spmv {mtx} --perm perms/{perm}/$mtx_name.perm"
